package com.zeyadgasser.playground.badhabits.list.viewmodel

import com.zeyadgasser.playground.architecture.presentation.InputHandler
import com.zeyadgasser.playground.architecture.presentation.Result
import com.zeyadgasser.playground.badhabits.domain.BadHabitRating
import com.zeyadgasser.playground.badhabits.domain.BadHabitsRepository
import com.zeyadgasser.playground.badhabits.list.viewmodel.BadHabitListState.EmptyState
import com.zeyadgasser.playground.badhabits.list.viewmodel.BadHabitListState.SuccessState
import com.zeyadgasser.playground.badhabits.sharedpresentation.BadHabitsPresentationMapper
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.onStart
import kotlinx.datetime.Clock
import kotlinx.datetime.LocalDate
import kotlinx.datetime.TimeZone
import kotlinx.datetime.format
import kotlinx.datetime.format.DayOfWeekNames
import kotlinx.datetime.format.char
import kotlinx.datetime.toLocalDateTime

class LoadBadHabitListInputHandler(
    private val repository: BadHabitsRepository,
    private val taskPresentationMapper: BadHabitsPresentationMapper,
) : InputHandler<LoadBadHabitListInput, BadHabitListState> {

    override fun invoke(input: LoadBadHabitListInput, currentState: BadHabitListState): Flow<Result> {
        return repository.getBadHabits().map { domainBadHabits ->
            val currentDate = getCurrentDateFormatted()
            val updatedBadHabits = domainBadHabits.map { badHabit ->
                // Check if a rating exists for the current date for this bad habit
                val hasTodayRating = badHabit.ratings.any { it.date == currentDate }
                if (!hasTodayRating) {
                    // If no rating for today, add a new one with value 0
                    val newRating = BadHabitRating(
                        id = 0L, // ID will be auto-generated by the DB on insert
                        ratingValue = 0,
                        date = currentDate
                    )
                    val updatedRatings = badHabit.ratings + newRating
                    // Update the bad habit in the repository
                    // We do this in a non-blocking way or as part of a larger transaction if needed
                    // For simplicity, directly call insertBadHabitWithRatings (which handles upsert)
                    repository.insertBadHabitWithRatings(badHabit.copy(ratings = updatedRatings))
                    badHabit.copy(ratings = updatedRatings) // Return updated domain object for mapping
                } else badHabit // No change needed if rating exists for today
            }
            taskPresentationMapper.mapToPresentationList(updatedBadHabits)
        }.map { if (it.isNotEmpty()) SuccessState(it, getCurrentDateLabel(), false) else EmptyState }
            .onStart { emit(SuccessState(emptyList(), getCurrentDateLabel(), true)) }
    }

    private fun getCurrentDateFormatted(): String = getCurrentDate().format(LocalDate.Format {
        dayOfMonth()
        char('/')
        monthNumber()
        char('/')
        year()
    })

    private fun getCurrentDateLabel(): String = getCurrentDate().format(LocalDate.Format {
        dayOfWeek(DayOfWeekNames.ENGLISH_FULL)
        char(',')
        char(' ')
        dayOfMonth()
        char('/')
        monthNumber()
        char('/')
        year()
    })

    private fun getCurrentDate(): LocalDate =
        Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault()).date
}
